name: publish

on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup java & plantuml
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: download, validate, install plantuml and its dependencies
      run: |
        curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar
        mv plantuml.jar /opt/plantuml.jar
        curl -o plantuml-jlatexmath.zip -L https://www.dropbox.com/s/ameybtbiqaszfs3/plantuml-jlatexmath.zip?dl=1
        unzip plantuml-jlatexmath.zip -d /opt
        echo $'#!/bin/sh -e\njava -jar /opt/plantuml.jar ${@}' >> "/usr/local/bin/plantuml"
        sudo chmod +x /usr/local/bin/plantuml

    - name: Install shpinx-tikz dependencies
      run: |
        sudo apt-get -y install texlive texlive-xetex texlive-pictures poppler-utils pnmtopng imagemagick ghostscript graphviz

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.x

    - name: Update pip & wheel
      run: |
        pip install -U pip wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: econnotes.sidkang.com